[package]
name = "material_color"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lazy_static = "1.4.0"

[build-dependencies]
serde = "1.0.160"
serde_json = "1.0.96"
anyhow = "1.0.71"