[package]
name = "material_color"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
lazy_static = "1.4.0"

[build-dependencies]
syn = "2.0.15"
serde = "1.0.160"
serde_json = "1.0.96"
anyhow = "1.0.71"
prettyplease = "0.2.4"